# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mousarium\Desktop\add_new_shiftui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import psycopg2
from contextlib import closing
from windows import err_box

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_request(object):

    def setupUi(self, new_request):
        new_request.setObjectName("new_request")
        new_request.resize(793, 96)
        self.centralwidget = QtWidgets.QWidget(new_request)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(793, 96))
        self.centralwidget.setMaximumSize(QtCore.QSize(793, 96))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.id_worker = QtWidgets.QLineEdit(self.centralwidget)
        self.id_worker.setObjectName("id_worker")
        self.verticalLayout_7.addWidget(self.id_worker)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.exp_date = QtWidgets.QLineEdit(self.centralwidget)
        self.exp_date.setObjectName("exp_date")
        self.verticalLayout.addWidget(self.exp_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.decline = QtWidgets.QPushButton(self.centralwidget)
        self.decline.setObjectName("decline")
        self.horizontalLayout_2.addWidget(self.decline)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        new_request.setCentralWidget(self.centralwidget)

        self.retranslateUi(new_request)
        QtCore.QMetaObject.connectSlotsByName(new_request)

    def retranslateUi(self, new_request):
        _translate = QtCore.QCoreApplication.translate
        new_request.setWindowTitle(_translate("new_request", "MainWindow"))
        self.label_4.setText(_translate("new_request", "ID_работника"))
        self.label_5.setText(_translate("new_request", "Длительность смены (в часах)"))
        self.decline.setText(_translate("new_request", "Добавить"))
        self.add.setText(_translate("new_request", "Отмена"))


class new_shift(QtWidgets.QMainWindow, Ui_new_request):
    def __init__(self, parent):
        super().__init__()
        self.err = err_box.err_box()
        self.setupUi(self)
        self.retranslateUi(self)
        self.show()
        self.parent = parent
        self.decline.clicked.connect(self.ad)
        self.add.clicked.connect(self.dc)

    def dc(self):
        self.close()

    def ad(self):
        errors = []
        id_workers = []
        with closing(psycopg2.connect(dbname='coursework', user=str(self.parent.logpas[0]),
                                      password=str(self.parent.logpas[1]), host='localhost')) as conn:
            cursor = conn.cursor()
            cursor.execute('select id_worker from workers')
            id_workers = cursor.fetchall()
        if not self.id_worker.text().isdigit():
            errors.append("Номер работника может содержать только цифры")
        if not (int(self.id_worker.text()), ) in id_workers:
            errors.append("Работника с таким номером не существует")
        if not self.exp_date.text().isdigit():
            errors.append("Интервал может содержать только цифры")
        # id_Worker make stable with parent.id in case
        if errors:
            self.error(errors)
        else:
            close_date = []
            with closing(psycopg2.connect(dbname='coursework', user=str(self.parent.logpas[0]),
                                          password=str(self.parent.logpas[1]), host='localhost')) as conn:
                cursor = conn.cursor()
                cursor.execute("select CURRENT_TIMESTAMP + interval '{0} hour'".format(int(self.exp_date.text())))
                close_date = cursor.fetchall()
            stroke = (int(self.id_worker.text()), close_date[0])
            with closing(psycopg2.connect(dbname='coursework', user=str(self.parent.logpas[0]),
                                          password=str(self.parent.logpas[1]), host='localhost')) as conn:
                try:
                    cursor = conn.cursor()
                    cursor.execute(
                        'insert into shifts (id_worker, close_date) values (%s, %s);',
                        stroke)
                except psycopg2.Error as e:
                    self.err.er_text += str(e)
                    self.err.show()
                finally:
                    if not self.err.isVisible():
                        conn.commit()
                        self.parent.update_screens()
            self.close()

    def error(self, colums):
        ertext = "\n".join(colums) + "\n"
        self.err.er_text.setText(ertext)
        self.err.show()




