# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mousarium\Documents\GitHub\CRM-provider\lab3cCot\ui_raw\add_new_shiftui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from windows import err_box
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_request(object):
    def setupUi(self, new_request):
        new_request.setObjectName("new_request")
        new_request.resize(793, 96)
        self.centralwidget = QtWidgets.QWidget(new_request)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(793, 96))
        self.centralwidget.setMaximumSize(QtCore.QSize(793, 96))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.id_shift = QtWidgets.QLineEdit(self.centralwidget)
        self.id_shift.setObjectName("id_shift")
        self.verticalLayout_4.addWidget(self.id_shift)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.id_worker = QtWidgets.QLineEdit(self.centralwidget)
        self.id_worker.setObjectName("id_worker")
        self.verticalLayout_7.addWidget(self.id_worker)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.exp_date = QtWidgets.QLineEdit(self.centralwidget)
        self.exp_date.setObjectName("exp_date")
        self.verticalLayout.addWidget(self.exp_date)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.decline = QtWidgets.QPushButton(self.centralwidget)
        self.decline.setObjectName("decline")
        self.horizontalLayout_2.addWidget(self.decline)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        new_request.setCentralWidget(self.centralwidget)

        self.retranslateUi(new_request)
        QtCore.QMetaObject.connectSlotsByName(new_request)

    def retranslateUi(self, new_request):
        _translate = QtCore.QCoreApplication.translate
        new_request.setWindowTitle(_translate("new_request", "MainWindow"))
        self.label_2.setText(_translate("new_request", "ID_смены"))
        self.label_4.setText(_translate("new_request", "ID_работника"))
        self.label_5.setText(_translate("new_request", "Длительность смены в часах"))
        self.decline.setText(_translate("new_request", "Добавить"))
        self.add.setText(_translate("new_request", "Отмена"))


class new_shift(QtWidgets.QMainWindow, Ui_new_request):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)
        self.show()
        self.decline.clicked.connect(self.ad)
        self.add.clicked.connect(self.dc)

    def dc(self):
        self.close()

    def ad(self):
        self.close()

    def error(self, colums):
        self.err = err_box.err_box()
        ertext = ""
        for item in colums:
            ertext += 'Пропущено поле "{}". Внесите данные\n'.format(item)
        print(ertext)
        self.err.er_text.setText(ertext)
        self.err.show()

    def regPas(self):
        errors = []
        if self.name.text() == "":
            errors.append("Имя")
        if self.phone.text() == "":
            errors.append("Номер телефона")
        if self.buss_pers.text() == "":
            errors.append("Номер личного дела")
        if self.email.text() == "":
            errors.append("EMAIL")
        if self.adress.text() == "":
            errors.append("Адрес")
        if self.med_book.text() == "":
            errors.append("Мед книжка")
        if self.position.currentText() == "":
            errors.append("Должность")
        if self.login.text() == "":
            errors.append("Логин")
        if self.passw.text() == "":
            errors.append("Пароль")
        if self.pass_check.text() != self.passw.text():
            errors.append("Пароль и проверка пароля.\nДанные не совпадают")
        self.error(errors)
