# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mousarium\Documents\GitHub\CRM-provider\lab3cCot\ui_raw\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import psycopg2
from contextlib import closing
from windows import (enterui, mainW, err_box)
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 187)
        Dialog.setMinimumSize(QtCore.QSize(400, 187))
        Dialog.setMaximumSize(QtCore.QSize(400, 187))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.login = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.login.setObjectName("login")
        self.horizontalLayout_2.addWidget(self.login)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.passw = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passw.setObjectName("passw")
        self.horizontalLayout_3.addWidget(self.passw)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Вход"))
        self.pushButton_2.setText(_translate("Dialog", "Отмена"))
        self.label.setText(_translate("Dialog", "Логин:"))
        self.label_2.setText(_translate("Dialog", "Пароль:"))


class login(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.err = err_box.err_box('Ошибка подключения к базе данных\nПроверьте правильность ввода')
        self.setupUi(self)
        self.retranslateUi(self)
        self.pushButton.clicked.connect(self.enter)
        self.pushButton_2.clicked.connect(self.decline)

    def decline(self):
        self.ent = enterui.enter()
        self.ent.show()
        self.close()

    def enter(self):
        log_pas = (self.login.text(), int(self.passw.text()))
        role = ''

        print(log_pas)

        try:
            conn = psycopg2.connect(dbname='coursework', user=str(log_pas[0]),
                                    password=log_pas[1], host='localhost')
            cur = conn.cursor()
            cur.execute('select groname from pg_group where (select usesysid from pg_user where usename = %s)'
                        ' = ANY (grolist);', (log_pas[0], ))
            role = cur.fetchone()[0]
            cur.close()
            conn.close()
        except psycopg2.Error as e:
            print(e)
            #self.err.er_text += str(e)
            self.err.show()
        if not self.err.isVisible():
            if log_pas[0] in ['admin', 'postgres']:
                role = 'admin'
            self.mainWin = mainW.mainW(log_pas, role)
            self.mainWin.show()
            self.close()
