# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Mousarium\Documents\GitHub\3C_cw\ui_raw\reg_diag.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import psycopg2
import random
from contextlib import closing
from windows import err_box
from windows import (enterui, err_box, mainW)
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        Dialog.setMinimumSize(QtCore.QSize(400, 400))
        Dialog.setMaximumSize(QtCore.QSize(400, 400))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setAutoFillBackground(False)
        self.name.setObjectName("name")
        self.horizontalLayout_4.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.phone = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.phone.setObjectName("phone")
        self.horizontalLayout_3.addWidget(self.phone)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.buss_pers = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.buss_pers.setObjectName("buss_pers")
        self.horizontalLayout_10.addWidget(self.buss_pers)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.email = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.email.setObjectName("email")
        self.horizontalLayout_15.addWidget(self.email)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.adress = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.adress.setObjectName("adress")
        self.horizontalLayout_6.addWidget(self.adress)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.med_book = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.med_book.setObjectName("med_book")
        self.horizontalLayout_14.addWidget(self.med_book)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.position = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position.sizePolicy().hasHeightForWidth())
        self.position.setSizePolicy(sizePolicy)
        self.position.setObjectName("position")
        self.position.addItem("")
        self.position.addItem("")
        self.horizontalLayout_18.addWidget(self.position)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_16.addWidget(self.label_10)
        spacerItem7 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.login = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.login.setObjectName("login")
        self.horizontalLayout_16.addWidget(self.login)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        spacerItem8 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.passw = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passw.setObjectName("passw")
        self.horizontalLayout_9.addWidget(self.passw)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem9 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.pass_check = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pass_check.setObjectName("pass_check")
        self.horizontalLayout_2.addWidget(self.pass_check)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Имя:"))
        self.label_2.setText(_translate("Dialog", "Номер телефона:"))
        self.label_4.setText(_translate("Dialog", "Номер личного дела:"))
        self.label_9.setText(_translate("Dialog", "EMAIL:"))
        self.label_5.setText(_translate("Dialog", "Адрес:"))
        self.label_8.setText(_translate("Dialog", "Номер медкнижки:"))
        self.label_12.setText(_translate("Dialog", "Должность:"))
        self.position.setItemText(0, _translate("Dialog", "Работник"))
        self.position.setItemText(1, _translate("Dialog", "Менеджер"))
        self.label_10.setText(_translate("Dialog", "Логин:"))
        self.label_11.setText(_translate("Dialog", "Пароль:"))
        self.label_3.setText(_translate("Dialog", "Подтвердите пароль:"))
        self.pushButton_2.setText(_translate("Dialog", "Зарегистрироваться"))
        self.pushButton.setText(_translate("Dialog", "Отмена"))


class reg_diag(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.ent = enterui.enter()
        self.setupUi(self)
        self.retranslateUi(self)
        self.pushButton_2.clicked.connect(self.regPas)
        self.pushButton.clicked.connect(self.decline)

    def decline(self):
        self.ent.show()
        self.close()

    def regPas(self):
        not_allow_names = r'1234567890,./\";:<>}{$@!*^&[]+-_#~`'
        not_allow_spec = r'/\";:<>}{$!*^&[]+-_@#~`'
        salary = 0
        position = self.position.currentText()
        self.err = err_box.err_box()
        ertext = ""
        if position == 'Менеджер':
            salary = 80000
            position = 'manager'
        elif position == 'Работник':
            salary = 40000
            position = 'worker'
        if any((c in not_allow_names) for c in self.name.text()):
            ertext += 'Имя не должно содержать специальные символы\n'
        if not self.phone.text().isdigit():
            ertext += 'Телефон должен содержать только цифры\n'
        if not self.buss_pers.text().isdigit():
            ertext += 'Номер личного дела должен содержать только цифры\n'
        if not len(self.email.text()) > 6:
            ertext += 'Почта не может быть короче 6 символов\n'
        if not self.med_book.text().isdigit():
            ertext += 'Номер медицинской книжки должен содержать только цифры\n'
        if not len(self.login.text()) > 4:
            ertext += 'Логин не может быть короче 4 символов\n'
        if not len(self.passw.text()) > 4:
            ertext += 'Пароль не может быть короче 4 символов\n'
        if not self.passw.text() == self.pass_check.text():
            ertext += 'Пароли не совпадают\n'
        if any((c in not_allow_spec) for c in self.adress.text()):
            ertext += 'Адрес может содержать только буквы и цифры\n'
        if ertext:
            self.err.er_text.setText(ertext)
            self.err.show()
        else:
            pas_log = self.login.text(), self.passw.text()
            if pas_log == ('postgres', 'ttblue2020'): return 1
            stroke = (
                salary, int(self.buss_pers.text()), int(self.phone.text()), str(self.name.text()),
                str(self.email.text()), int(self.med_book.text()), str('***********'), random.randint(1, 3),
                str(self.adress.text()),
                position)
            with closing(psycopg2.connect(dbname='coursework', user='postgres',
                                          password='ttblue2020', host='localhost')) as conn:
                cursor = conn.cursor()
                try:
                    cursor.execute(
                        'insert into workers (salary_worker, private_buss_worker, phone_number_worker, name_worker,'
                        ' e_mail_worker, med_book_number, login_worker, id_group, adress, " position_worker") values'
                        ' (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);',
                        stroke)
                except psycopg2.Error as e:
                    self.err = err_box.err_box(str(e))
                    print(e)
                    self.err.show()
                finally:
                    conn.commit()
            if not self.err.isVisible():
                try:
                    conn = psycopg2.connect(dbname='coursework', user='postgres',
                                            password='ttblue2020', host='localhost')
                    cursor = conn.cursor()
                    cursor.execute("create user {0} in group {1} password '{2}';".format(
                        self.login.text(), position,
                        self.passw.text()))
                except psycopg2.Error as e:
                    self.err = err_box.err_box(str(e))
                    print(e)
                    self.err.show()
                finally:
                    if not self.err.isVisible():
                        conn.commit()
            if self.err.isHidden():
                self.mainWin = mainW.mainW(pas_log, position)
                self.mainWin.show()
                self.close()
